# Generated by Django 5.2.2 on 2025-06-26 13:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0002_rename_tourage_tourageprice_tour_end_sale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('age_prices', models.ManyToManyField(to='tours.tourageprice')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer')),
                ('extra_prices', models.ManyToManyField(to='tours.tourextraprice')),
                ('tour', models.ForeignKey(limit_choices_to={'end_sale__gte': datetime.date(2025, 6, 26), 'is_active': True, 'start_sale__lte': datetime.date(2025, 6, 26)}, on_delete=django.db.models.deletion.PROTECT, to='tours.tour')),
            ],
        ),
    ]
