# Generated by Django 5.2.2 on 2025-06-27 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_tourproxy_alter_sale_agent_alter_sale_tour'),
        ('tours', '0003_remove_tour_convert_ask_sell_remove_tour_insurance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Sold Tours',
                'verbose_name_plural': 'Sold Tours',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.sale',),
        ),
        migrations.AlterField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'is_staff': True, 'status': 'agent'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tour'),
        ),
    ]
