# Generated by Django 5.2.2 on 2025-06-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleproxy_alter_sale_agent_alter_sale_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='processed_at',
            field=models.DateField(),
        ),
    ]
