# Generated by Django 5.2.2 on 2025-06-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_processed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'My Sold Tours', 'verbose_name_plural': 'My Sold Tours'},
        ),
        migrations.AlterModelOptions(
            name='saleproxy',
            options={'verbose_name': 'Sold Tours History', 'verbose_name_plural': 'Sold Tours History'},
        ),
    ]
