# Generated by Django 5.2.2 on 2025-06-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_options_alter_saleproxy_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleProxy',
        ),
        migrations.CreateModel(
            name='SaleHistoryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Sold Tours History',
                'verbose_name_plural': 'Sold Tours History',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.sale',),
        ),
    ]
