# Generated by Django 5.2.2 on 2025-06-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_delete_saleproxy_salehistoryproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], default='percentage'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='processed_at',
            field=models.DateField(verbose_name='Tour Date'),
        ),
    ]
