# Generated by Django 5.2.2 on 2025-06-28 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale_discount_sale_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 28, 9, 55, 8, 57974, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage %'), ('amount', 'Amount $')], default='percentage'),
        ),
    ]
