# Generated by Django 5.2.2 on 2025-06-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sale_created_at_alter_sale_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ManyToManyField(to='sales.customer'),
        ),
    ]
