# Generated by Django 5.2.2 on 2025-06-28 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_region'),
        ('sales', '0010_customer_age_customer_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='hotel',
            field=models.ManyToManyField(to='common.hotel'),
        ),
        migrations.AddField(
            model_name='sale',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.region'),
        ),
    ]
