# Generated by Django 5.2.2 on 2025-06-28 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_region'),
        ('sales', '0012_alter_sale_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.region'),
        ),
    ]
