# Generated by Django 5.2.2 on 2025-06-28 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_sale_region'),
        ('tours', '0006_alter_tour_allotment_alter_tour_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAgePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tourageprice')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleExtraPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer')),
                ('extra_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tourextraprice')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.sale')),
            ],
        ),
    ]
