# Generated by Django 5.2.2 on 2025-06-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_saleageprice_saleextraprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='age_prices',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='extra_prices',
        ),
    ]
