# Generated by Django 5.2.2 on 2025-06-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_delete_salehistoryproxy_soldtours_soldtoursageprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(choices=[('percentage', '%'), ('amount', '$')], default='percentage'),
        ),
    ]
