# Generated by Django 5.2.2 on 2025-06-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_sale_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleageprice',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='age_prices', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='saleextraprice',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_prices', to='sales.sale'),
        ),
    ]
