# Generated by Django 5.2.2 on 2025-07-02 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_saleageprice_sale_alter_saleextraprice_sale'),
        ('tours', '0009_alter_tourageprice_max_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tour', verbose_name='Tour'),
        ),
    ]
