# Generated by Django 5.2.2 on 2025-07-04 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_sale_tour'),
        ('tours', '0009_alter_tourageprice_max_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tour', verbose_name='Tour Name'),
        ),
    ]
