# Generated by Django 5.2.2 on 2025-07-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_remove_customer_age_customer_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='area',
            field=models.CharField(max_length=255, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='sale',
            name='pick_up_time',
            field=models.TimeField(null=True, verbose_name='Pickup Time'),
        ),
    ]
