# Generated by Django 5.2.2 on 2025-07-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_sale_area_sale_pick_up_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_max',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Max'),
        ),
    ]
