# Generated by Django 5.2.2 on 2025-07-05 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_child'),
        ('sales', '0023_sale_total_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='adult',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.adult'),
        ),
        migrations.AddField(
            model_name='sale',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.child'),
        ),
    ]
