# Generated by Django 5.2.2 on 2025-07-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_sale_adult_sale_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='child',
        ),
    ]
