# Generated by Django 5.2.2 on 2025-07-07 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_adult_options'),
        ('sales', '0025_remove_sale_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.adult')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
            ],
        ),
    ]
