# Generated by Django 5.2.2 on 2025-07-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_extrasale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraSale',
        ),
    ]
