# Generated by Django 5.2.2 on 2025-07-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_delete_extrasale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='adult',
        ),
    ]
