# Generated by Django 5.2.2 on 2025-07-16 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_remove_sale_adult'),
        ('tours', '0013_remove_tourextraprice_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='voucher_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='tours.tour', verbose_name='Voucher Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='tours.tour', verbose_name='Tour Name'),
        ),
    ]
