# Generated by Django 5.2.2 on 2025-07-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_sale_voucher_number_alter_sale_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='voucher_number',
        ),
    ]
