# Generated by Django 5.2.2 on 2025-07-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_remove_sale_voucher_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleageprice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='saleextraprice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
