# Generated by Django 5.2.2 on 2025-07-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_saleageprice_is_active_saleextraprice_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleageprice',
            name='is_active',
        ),
    ]
