# Generated by Django 5.2.2 on 2025-07-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_remove_saleageprice_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleextraprice',
            name='is_active',
        ),
        migrations.AddField(
            model_name='saleextraprice',
            name='sale_status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivate', 'Deactivate')], default='active', max_length=10, verbose_name='Sale Status'),
        ),
    ]
