# Generated by Django 5.2.2 on 2025-07-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_remove_saleextraprice_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='passport',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
