version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dubai_bonus_db
    environment:
      POSTGRES_DB: dubai_bonus
      POSTGRES_USER: dubai_bonus
      POSTGRES_PASSWORD: dubai_bonus
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: ./entrypoint.sh.sh
    container_name: dubai_bonus_web
    ports:
      - "8010:8010"
    depends_on:
      - db
    environment:
      POSTGRES_DB: dubai_bonus
      POSTGRES_USER: dubai_bonus
      POSTGRES_PASSWORD: dubai_bonus
      DB_HOST: db

volumes:
  postgres_data:
