# Generated by Django 5.2.2 on 2025-06-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_pickup', models.BooleanField(default=False, verbose_name='Is Pickup')),
                ('concept', models.CharField(max_length=100, verbose_name='Concept')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('allotment', models.BooleanField(default=False, verbose_name='Allotment')),
                ('duration', models.CharField(max_length=100, verbose_name='Duration')),
                ('sale_status', models.CharField(max_length=100, verbose_name='Sale Status')),
                ('convert_ask_sell', models.CharField(max_length=100, verbose_name='Convert Ask Sell')),
                ('insurance', models.BooleanField(blank=True, null=True, verbose_name='Insurance')),
                ('transfer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.transfertype', verbose_name='Transfer Type')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.tourtype', verbose_name='Tour Type')),
            ],
        ),
        migrations.CreateModel(
            name='TourAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('min_age', models.FloatField(verbose_name='Minimum Age')),
                ('max_age', models.FloatField(verbose_name='Maximum Age')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=28, verbose_name='Price')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.currency', verbose_name='Currency')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tour', verbose_name='Tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourExtraPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=28, verbose_name='Price')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.currency', verbose_name='Currency')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tour', verbose_name='Tour')),
            ],
        ),
    ]
