# Generated by Django 5.2.2 on 2025-06-26 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourAge',
            new_name='TourAgePrice',
        ),
        migrations.AddField(
            model_name='tour',
            name='end_sale',
            field=models.DateField(default=datetime.datetime(2025, 6, 26, 13, 17, 34, 868197, tzinfo=datetime.timezone.utc), verbose_name='End Sale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='tour',
            name='start_sale',
            field=models.DateField(default=datetime.datetime(2025, 6, 26, 13, 17, 40, 579564, tzinfo=datetime.timezone.utc), verbose_name='Start Sale'),
            preserve_default=False,
        ),
    ]
