# Generated by Django 5.2.2 on 2025-06-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_tour_convert_ask_sell_remove_tour_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='supplier',
            field=models.BooleanField(default=False, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='concept',
            field=models.CharField(choices=[('standard', 'Standard'), ('individual', 'Individual'), ('free', 'Free'), ('group', 'Group')], default='standard', verbose_name='Concept'),
        ),
    ]
