# Generated by Django 5.2.2 on 2025-06-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_supplier_alter_tour_concept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='code',
        ),
    ]
