# Generated by Django 5.2.2 on 2025-06-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_remove_tour_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='allotment',
            field=models.PositiveIntegerField(default=0, verbose_name='Allotment(count)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.CharField(max_length=100, verbose_name='Duration(days)'),
        ),
    ]
