# Generated by Django 5.2.2 on 2025-07-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_tour_allotment_alter_tour_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Duration(days)'),
        ),
    ]
