# Generated by Django 5.2.2 on 2025-07-02 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_region_options'),
        ('tours', '0007_alter_tour_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='common.hotel'),
            preserve_default=False,
        ),
    ]
