# Generated by Django 5.2.2 on 2025-07-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tour_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourageprice',
            name='max_age',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Age'),
        ),
        migrations.AlterField(
            model_name='tourageprice',
            name='min_age',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Age'),
        ),
    ]
