# Generated by Django 5.2.2 on 2025-07-07 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_adult_options'),
        ('tours', '0009_alter_tourageprice_max_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourageprice',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='tourageprice',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='tourageprice',
            name='name',
        ),
        migrations.AddField(
            model_name='tourageprice',
            name='adult',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.adult', verbose_name='Age Category'),
        ),
    ]
