# Generated by Django 5.2.2 on 2025-07-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_remove_tourageprice_adult_tourageprice_max_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourageprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=28, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='tourextraprice',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tourextraprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=28, null=True, verbose_name='Price'),
        ),
    ]
