# Generated by Django 5.2.2 on 2025-07-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_tourageprice_price_alter_tourextraprice_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourextraprice',
            name='price',
        ),
        migrations.AddField(
            model_name='tourextraprice',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tourextraprice',
            name='child_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tourextraprice',
            name='toddle_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
