# Generated by Django 5.2.2 on 2025-06-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
            },
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='tourtype',
            options={'verbose_name': 'Tour Type', 'verbose_name_plural': 'Tour Types'},
        ),
        migrations.AlterModelOptions(
            name='transfertype',
            options={'verbose_name': 'Transfer Type ', 'verbose_name_plural': 'Transfer Types '},
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Currency Name'),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tour Type Name'),
        ),
        migrations.AlterField(
            model_name='transfertype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Transfer Type Name'),
        ),
    ]
