# Generated by Django 5.2.2 on 2025-06-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
    ]
