# Generated by Django 5.2.2 on 2025-07-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_region_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('min_age', models.IntegerField(verbose_name='Minimum Age')),
                ('max_age', models.IntegerField(verbose_name='Maximum Age')),
            ],
        ),
    ]
