# Generated by Django 5.2.2 on 2025-07-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='max_age',
            field=models.FloatField(verbose_name='Maximum Age'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='min_age',
            field=models.FloatField(verbose_name='Minimum Age'),
        ),
    ]
