# Generated by Django 5.2.2 on 2025-07-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_adult_max_age_alter_adult_min_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('min_age', models.FloatField(verbose_name='Minimum Age')),
                ('max_age', models.FloatField(verbose_name='Maximum Age')),
            ],
        ),
    ]
