# Generated by Django 5.2.2 on 2025-07-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_child'),
        ('sales', '0025_remove_sale_child'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Child',
        ),
    ]
