# Generated by Django 5.2.2 on 2025-07-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_delete_child'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adult',
            options={'verbose_name': 'Adult', 'verbose_name_plural': 'Adults'},
        ),
    ]
